GET http://localhost:3000/ping


###


POST http://localhost:3000/register
Content-Type:application/json

{
   "email":"juan2@geekshubs.com",
   "password":"A12345678!"
}


###

POST http://localhost:3000/login
Content-Type:application/json

{
   "email":"juan@geekshubs.com",
   "password":"12345"
}

###

GET http://localhost:3000/me
Authorization:c1c9b8c0-537c-44aa-a88e-6097e163083d


###

GET http://localhost:3000/logout
Authorization:c1c9b8c0-537c-44aa-a88e-6097e163083d